version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-scrapper
    env_file:
      - docker.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq
    networks:
      - node-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-scrapper
    ports:
      - '9000:9000'
    restart: on-failure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.volume/portainer/data:/data
    networks:
      - node-network

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "8001:8001"
      - "6379:6379"
    restart: on-failure
    networks:
      - node-network

networks:
  node-network:
    driver: bridge