version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq-scrapper
    env_file:
      - docker.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-scrapper
    ports:
      - '9000:9000'
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.volume/portainer/data:/data