version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    env_file:
      - docker.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq
