###

POST localhost:3000/api/v1/posts
Content-Type: application/json

{
"url": "https://vnexpress.net/messi-mbappe-giup-psg-thang-dam-marseille-4575108.html"
}

###

POST localhost:3000/api/v1/posts
Content-Type: application/json

{
"url": "https://vnexpress.net/lewandowski-barca-can-thang-truoc-khi-nghi-den-thang-dep-4583007.html"
}


###

GET localhost:3000/api/v1/posts
Accept: application/json

###

GET localhost:3000/api/v1/posts/testMessage
Accept: application/json