// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: domains/post_message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audit *AuditableEntity `protobuf:"bytes,1,opt,name=Audit,proto3" json:"Audit,omitempty"`
	Id    string           `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Title string           `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
}

func (x *Post) Reset() {
	*x = Post{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domains_post_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_domains_post_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_domains_post_message_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetAudit() *AuditableEntity {
	if x != nil {
		return x.Audit
	}
	return nil
}

func (x *Post) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type PostImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Audit  *AuditableEntity `protobuf:"bytes,1,opt,name=Audit,proto3" json:"Audit,omitempty"`
	Id     string           `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Url    string           `protobuf:"bytes,3,opt,name=Url,proto3" json:"Url,omitempty"`
	PostId string           `protobuf:"bytes,4,opt,name=PostId,proto3" json:"PostId,omitempty"`
}

func (x *PostImage) Reset() {
	*x = PostImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_domains_post_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostImage) ProtoMessage() {}

func (x *PostImage) ProtoReflect() protoreflect.Message {
	mi := &file_domains_post_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostImage.ProtoReflect.Descriptor instead.
func (*PostImage) Descriptor() ([]byte, []int) {
	return file_domains_post_message_proto_rawDescGZIP(), []int{1}
}

func (x *PostImage) GetAudit() *AuditableEntity {
	if x != nil {
		return x.Audit
	}
	return nil
}

func (x *PostImage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PostImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PostImage) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

var File_domains_post_message_proto protoreflect.FileDescriptor

var file_domains_post_message_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x5f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x1a, 0x25, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x73, 0x2f, 0x61, 0x75,
	0x64, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a, 0x04, 0x50,
	0x6f, 0x73, 0x74, 0x12, 0x2d, 0x0a, 0x05, 0x41, 0x75, 0x64, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x75, 0x64, 0x69,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x05, 0x41, 0x75, 0x64,
	0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x22, 0x74, 0x0a, 0x09, 0x50, 0x6f, 0x73, 0x74,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x41, 0x75, 0x64, 0x69, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x2e, 0x41, 0x75,
	0x64, 0x69, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x05, 0x41,
	0x75, 0x64, 0x69, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x49, 0x64, 0x42, 0x05,
	0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_domains_post_message_proto_rawDescOnce sync.Once
	file_domains_post_message_proto_rawDescData = file_domains_post_message_proto_rawDesc
)

func file_domains_post_message_proto_rawDescGZIP() []byte {
	file_domains_post_message_proto_rawDescOnce.Do(func() {
		file_domains_post_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_domains_post_message_proto_rawDescData)
	})
	return file_domains_post_message_proto_rawDescData
}

var file_domains_post_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_domains_post_message_proto_goTypes = []interface{}{
	(*Post)(nil),            // 0: domain.Post
	(*PostImage)(nil),       // 1: domain.PostImage
	(*AuditableEntity)(nil), // 2: domain.AuditableEntity
}
var file_domains_post_message_proto_depIdxs = []int32{
	2, // 0: domain.Post.Audit:type_name -> domain.AuditableEntity
	2, // 1: domain.PostImage.Audit:type_name -> domain.AuditableEntity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_domains_post_message_proto_init() }
func file_domains_post_message_proto_init() {
	if File_domains_post_message_proto != nil {
		return
	}
	file_domains_auditableEntity_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_domains_post_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Post); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_domains_post_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_domains_post_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_domains_post_message_proto_goTypes,
		DependencyIndexes: file_domains_post_message_proto_depIdxs,
		MessageInfos:      file_domains_post_message_proto_msgTypes,
	}.Build()
	File_domains_post_message_proto = out.File
	file_domains_post_message_proto_rawDesc = nil
	file_domains_post_message_proto_goTypes = nil
	file_domains_post_message_proto_depIdxs = nil
}
