basePath: /api/v1
definitions:
  models.Post:
    properties:
      createdAt:
        type: string
      id:
        type: string
      modifiedAt:
        type: string
      postImages:
        items:
          $ref: '#/definitions/models.PostImages'
        type: array
      title:
        type: string
    type: object
  models.PostImages:
    properties:
      createdAt:
        type: string
      id:
        type: string
      modifiedAt:
        type: string
      postId:
        type: string
      url:
        type: string
    type: object
  service.createPostRequest:
    properties:
      url:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /posts:
    get:
      consumes:
      - application/json
      description: Get all posts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Post'
            type: array
        "500":
          description: Internal Server Error
          schema: {}
      summary: Get all posts
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: Create post
      parameters:
      - description: URL of the website you want to crawl
        in: body
        name: post
        required: true
        schema:
          $ref: '#/definitions/service.createPostRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Post'
            type: array
      summary: Create post
      tags:
      - posts
swagger: "2.0"
